case = "when", ws, inputs_spec, ws, "=", ws, input_val_spec, nl, { case_output };

case_output = output, ws, "=", ws, number;

output = "out", "[", number_dec, "]"
input = "in", "[", number_dec, "]";

inputs_spec = "in";
	| "(" { input, ",", ws } ")";
input_val_spec = number_bin
	| "(", { bin_value, ",", ws }, ")";

bin_value = bit | input;

bit = "0" | "1";
digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";
number_dec = { digit };
number_bin = { bit };
number = ( number_dec, [ "." ] ) | number_bin;

ws = one_ws, { one_ws };
one_ws = " " | "\t";
nl = "\n", { "\n" };